### ISSUE TITLE
Translate to Norwegian

### ISSUE THREAD

**Issue by portlandnorway** [portlandnorway/vif-baseball#3]

**Comment by alexguilford** [comment]
Perhaps we can get cracking on the translating using ChatGPT, then have someone who is competent quality check for us.

**Comment by alexguilford** [comment]
Not like we're providing life and death info here.. just need to make sure we have the guts of it correct.

**Comment by portlandnorway** [comment]
Yeah i'm just procastinating on this shit. Good idea with GPT.

**Comment by portlandnorway** [comment]
Translated all content to Norwegian with the wife and GPT. Feel free to have your spouses or yourselves look over @alexguilford and @alecImTooGoodForGitHub
