### ISSUE TITLE
Language toggle

### ISSUE THREAD

**Issue by portlandnorway** [portlandnorway/vif-baseball#7]

**Comment by alexguilford** [comment]
Not sure what you're thinking here, but would the simplest approach be just to use a plug-in? i.e. gTranslate or something similar. Obviously, we want English, but it could be beneficial to have a Spanish option, as well.

**Comment by portlandnorway** [comment]
Yeah for sure, let the user decide. Google is an easy win.

**Comment by portlandnorway** [comment]
We decided to just set the site in Norwegian, which enables google translate for americans/hispanics/other that have browser settings to their native language. Good enough for now.
